/*
-- Query: select * from coffeshop.coffe
LIMIT 0, 1000

-- Date: 2023-10-07 23:56
*/
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (1,'Еспресо з гарячою водою створюють легкий шар крему, завершуючи цей дивовижно насичений стакан з глибиною та нюансами.\\n\" + \"Професійний по...',2.00,'caffe-americano.jpg','Кава Американо',50.00,'30.00',50.00,2.10,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (2,'Рівна комбінація свіжоприготованої кави і обігрітої молока створюють одну неймовірно смачну кавову напій, який дивно змішано.',2.00,'caffe-misto.jpg','Кава Місто',50.00,'30.00',50.00,2.60,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (3,'Еспресо з гарячою водою, щоб утворити легкий шар крему, приготоване з нашим Starbucks® Blonde Roast для додатково гладенької, трохи солодкої і нюансо...',2.00,'caffe-americano.jpg','Світла Кава Американо',50.00,'30.00',50.00,2.79,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (4,'Світло обсмажена кава, яка є ніжною, м\'якою та ароматною. Легко п\'ється сама по собі і смачно з молоком, цукром або ароматизована ванільним, ...',2.00,'dark-roast-coffee.jpg','Світла Кава Ростер',50.00,'40.00',50.00,2.05,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (5,'Ця повнотіла кава темного обсмажування з виразними, кріпкими смаками показує наше мистецтво обсмажування і змішування - необхідний бленд ...',2.00,'dark-roast-coffee.jpg','Кава Темний Ростер',50.00,'150.00',50.00,2.20,'зерна');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (6,'Від нашого першого магазину на ринку Пайка Плейс в Сіетлі до наших кав\'ярень по всьому світу, клієнти просили про свіжозаварену каву, якою ...',2.00,'dark-roast-coffee.jpg','Кава Пайк Плейс® Ростер',50.00,'28.00',50.00,2.80,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (7,'Від нашого першого магазину на ринку Пайка Плейс в Сіетлі до наших кав\'ярень по всьому світу, клієнти просили про свіжозаварену каву, якою ...',1.00,'dark-roast-coffee.jpg','Безкофеїнова Кава Пайк Плейс® Ростер',50.00,'30.00',50.00,2.25,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (8,'Темна, насичена еспресо чекає під густим шаром молочної піни. Це - результат мистецтва і вправності бариста.',2.00,'cappuccino.jpg','Капучино',50.00,'40.00',50.00,2.59,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (9,'Наша дуже ніжна і трохи солодка Блонд-еспресо чекає під густим шаром піни. Цей капучіно має розкішну текстуру і бархатисту, пінку з холодни...',2.00,'cappuccino.jpg','Світле Капучино',50.00,'40.00',50.00,2.34,'зерна');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (10,'Наша гладенька підписна кава Еспресо з багатим смаком і карамельною солодкістю є в самому серці всього, що ми робимо.',2.00,'espresso.jpg','Еспресо',50.00,'40.00',50.00,2.89,'молота');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (11,'Наше багате еспресо з горошинкою пареного молока та піни. Класика європейського стилю.',2.00,'espresso-macchiato.jpg','Еспресо Макіато',50.00,'60.00',50.00,2.18,'зерна');
INSERT INTO `` (`id`,`coffee_compos`,`delivery_price`,`image`,`name`,`net_weight`,`producer`,`quantity`,`selling_price`,`type`) VALUES (12,'Гладенькі рістретто-шоти еспресо отримують відповідну кількість пареного цілого молока, щоб створити смак, який не занадто крепкий, не за...',2.00,'flat-white.jpg','Флат Вайт',50.00,'30.00',50.00,2.75,'молота');
